// Generated by CoffeeScript 1.10.0
(function () {
    var path;

    path = {
        src: {
            views: './source/',
            scss: './source/scss',
            css: './source/css',
            js: './source/js',
            images: './source/img'
        },
        dest: {
            views: './build/',
            css: './build/css',
            js: './build/js',
            images: './build/img'
        }
    };

    module.exports = {
        path: path
    };

}).call(this);
